### ISSUE TITLE
Crashes with NPE if unknown badges are in the mix

### ISSUE THREAD

**Issue by zeichenreihe** [OrnitheMC/modmenu#4]
Modmenu crashes with a `NullPointerException` at this access to `badge` in `drawBadge`.
This is because `mod.getBadges()` returns a set containing at least one `null`.

https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/ModBadgeRenderer.java#L28-L37

An implementation for `Mod.getBadges()` is here:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/fabric/FabricMod.java#L226-L229
This field is set here:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/fabric/FabricMod.java#L94-L111
Even tho there are more badges added in other code, no code adds `null`. So it comes from the contructor of `ModMenuData`:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/fabric/FabricMod.java#L335-L339
And that shows us the problem:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/Mod.java#L153-L155
Here, the getter lambda can return `null`, if the given badge key doesn't exist.

To fix this, this should filter it in some way. It might also be a good idea to report this bug to upstream. I don't know if upsteam is affected or not.

Stack Trace:
```
Caused by: java.lang.NullPointerException
	at com.terraformersmc.modmenu.util.mod.ModBadgeRenderer.drawBadge(ModBadgeRenderer.java:33) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at com.terraformersmc.modmenu.util.mod.ModBadgeRenderer.lambda$draw$0(ModBadgeRenderer.java:29) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_392]
	at com.terraformersmc.modmenu.util.mod.ModBadgeRenderer.draw(ModBadgeRenderer.java:29) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.render(ModListEntry.java:75) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.renderEntry(EntryListWidget.java:28) ~[1.12.2-TRv0.8.2-named-711666161528F3329D7A8C8C611232C03E2D58B845ABA1B8F40897F5800EAE50.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.renderList(ModListWidget.java:246) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at net.minecraft.client.gui.widget.ListWidget.render(ListWidget.java:194) ~[1.12.2-TRv0.8.2-named-711666161528F3329D7A8C8C611232C03E2D58B845ABA1B8F40897F5800EAE50.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:321) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:947) ~[1.12.2-TRv0.8.2-named-711666161528F3329D7A8C8C611232C03E2D58B845ABA1B8F40897F5800EAE50.jar:?]
	... 6 more
```

**Comment by SpaceWalkerRS** [comment]
it looks like [upstream](https://github.com/TerraformersMC/ModMenu/blob/5d640d66a3e182889f84075d8fded0470534dbf5/src/main/java/com/terraformersmc/modmenu/util/mod/Mod.java#L152) is also affected by this, unless they filter the input elsewhere
